version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: reminder_db
    environment:
      POSTGRES_DB: reminder_system
      POSTGRES_USER: reminder_user
      POSTGRES_PASSWORD: reminder_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - reminder_network

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: reminder_n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Tunis
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=reminder_system
      - DB_POSTGRESDB_USER=reminder_user
      - DB_POSTGRESDB_PASSWORD=reminder_password
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - reminder_network

  # Web Application
  webapp:
    build: .
    container_name: reminder_webapp
    environment:
      - DATABASE_URL=postgresql://reminder_user:reminder_password@postgres:5432/reminder_system
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook
      - N8N_WEBHOOK_BASE=http://n8n:5678/webhook
      - SCHEDULE_WEBHOOK_URL=http://n8n:5678/webhook/schedule-reminder
      - IMMEDIATE_WEBHOOK_URL=http://n8n:5678/webhook/send-notification
      - WEBHOOK_BASE_URL=http://webapp:3000
      - TZ=Africa/Tunis
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - n8n
    networks:
      - reminder_network

volumes:
  postgres_data:
  n8n_data:

networks:
  reminder_network:
    driver: bridge
